# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-Wrapper
version:      0.08
version_from: lib/DBIx/Wrapper.pm
installdirs:  site
requires:
    Carp:                          0
    DBI:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
